name: sfw

services:
  db:
    image: postgres
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./app/.env
    restart: always

volumes:
  postgres_data:
